import type { Business } from "./types";

// ══════════════════════════════════════════════════════════════════════════════
// REAL BUSINESSES - All businesses below are verified as real and operating
// ══════════════════════════════════════════════════════════════════════════════

export const realBusinesses: Business[] = [
  // ────────────────────────────────────────────────────────────────────────────
  // AMSTERDAM
  // ────────────────────────────────────────────────────────────────────────────

  // === CLUBS / PARENCLUBS ===
  {
    id: "real-001",
    name: "Fata Morgana",
    slug: "fata-morgana",
    city_slug: "amsterdam",
    category_slugs: ["clubs", "saunaclubs"],
    primary_category: "clubs",
    description:
      "Fata Morgana is een van de grootste en meest luxueuze parenclubs van Europa, gelegen in Muiden vlakbij Amsterdam. De club staat bekend als de nummer 1 swingersclub van Nederland en biedt uitgebreide faciliteiten waaronder sauna, zwembad en themaruimtes. Uitsluitend voor paren en trio's; singles zijn niet toegestaan.",
    short_description:
      "Luxe parenclub bij Amsterdam, uitgeroepen tot beste swingersclub van Nederland.",
    address: "Muiden (bij Amsterdam)",
    postal_code: "1398 AB",
    phone: "+31 294 261 561",
    website: "https://www.fatamorgana.nl",
    image_url: "/screenshots/fata-morgana.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 4,
    is_verified: true,
    is_featured: true,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },
  {
    id: "real-002",
    name: "Sameplace",
    slug: "sameplace",
    city_slug: "amsterdam",
    category_slugs: ["clubs"],
    primary_category: "clubs",
    description:
      "Sameplace is een gezellige erotische bar en swingersclub aan de Nassaukade in Amsterdam-West. De club biedt een toegankelijke sfeer die geschikt is voor beginners en ervaren swingers. Bekende thema-avonden waaronder fetish nights, bi-avonden en mannenavonden. Accepteert uitsluitend contant geld.",
    short_description:
      "Gezellige swingersclub aan de Nassaukade, ideaal voor beginners met diverse thema-avonden.",
    address: "Nassaukade 120, Amsterdam",
    postal_code: "1052 EC",
    phone: "+31 20 475 1981",
    website: "https://www.sameplace.nl",
    image_url: "/screenshots/sameplace.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 2,
    is_verified: true,
    is_featured: false,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },

  // === STRIPCLUBS ===
  {
    id: "real-003",
    name: "BonTon",
    slug: "bonton-amsterdam",
    city_slug: "amsterdam",
    category_slugs: ["stripclubs"],
    primary_category: "stripclubs",
    description:
      "BonTon is de meest luxueuze stripclub van Amsterdam, gevestigd in een prachtig grachtenpand aan de Stadhouderskade. Opgericht in 2019, biedt de club een stijlvol interieur, VIP-ervaringen en verwelkomt ook stellen en gemengde groepen. Beoordeeld met 4.3 sterren op Google.",
    short_description:
      "Meest luxueuze stripclub van Amsterdam in een prachtig grachtenpand, ook voor stellen.",
    address: "Stadhouderskade, Amsterdam",
    postal_code: "1071 ZD",
    website: "https://www.stripclub-bonton.com",
    image_url: "/screenshots/bonton-amsterdam.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 4,
    is_verified: true,
    is_featured: true,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },
  {
    id: "real-005",
    name: "Casa Rosso",
    slug: "casa-rosso",
    city_slug: "amsterdam",
    category_slugs: ["stripclubs", "clubs"],
    primary_category: "stripclubs",
    description:
      "Casa Rosso is een legendarisch erotisch theater in de Red Light District met meer dan 50 jaar ervaring. De shows duren 60-90 minuten met gevarieerde acts waaronder live optredens en stripshows. Een van de beroemdste erotische showlocaties van Nederland.",
    short_description:
      "Legendarisch erotisch theater in de Red Light District met 50+ jaar ervaring.",
    address: "Oudezijds Achterburgwal, Amsterdam",
    postal_code: "1012 DS",
    website: "https://www.casarosso.nl",
    image_url: "/screenshots/casa-rosso.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 3,
    is_verified: true,
    is_featured: true,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },

  // === PRIVEHUIZEN / SEXCLUBS ===
  {
    id: "real-006",
    name: "Club Golden Key",
    slug: "club-golden-key",
    city_slug: "amsterdam",
    category_slugs: ["privehuizen", "clubs"],
    primary_category: "privehuizen",
    description:
      "Club Golden Key is een gerenommeerde seksclub aan de Overtoom, opgericht in 1987. De club beschikt over 8 privekamers en een selectie van dames. Beoordeeld met 4.1 sterren op Google. Gelegen nabij het Vondelpark in een discrete omgeving.",
    short_description:
      "Gevestigde seksclub aan de Overtoom sinds 1987, met privekamers nabij het Vondelpark.",
    address: "Overtoom 294, Amsterdam",
    postal_code: "1054 JC",
    website: "https://www.clubgoldenkey.nl",
    image_url: "/screenshots/club-golden-key.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 3,
    is_verified: true,
    is_featured: false,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },
  {
    id: "real-008",
    name: "Asmara",
    slug: "asmara",
    city_slug: "amsterdam",
    category_slugs: ["privehuizen", "erotische-massage"],
    primary_category: "privehuizen",
    description:
      "Asmara is het eerste door de gemeente Amsterdam vergunde bordeel, bekend sinds 1985 als een van de beste van Amsterdam. Gelegen aan de Willem de Zwijgerlaan biedt de club high-end faciliteiten, transparante prijzen en gespecialiseerde erotische massages.",
    short_description:
      "Eerste vergunde bordeel van Amsterdam sinds 1985, bekend om high-end service en faciliteiten.",
    address: "Willem de Zwijgerlaan 70, Amsterdam",
    postal_code: "1056 JT",
    phone: "+31 20 618 4069",
    website: "https://www.bordello.amsterdam",
    image_url: "/screenshots/asmara.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 3,
    is_verified: true,
    is_featured: true,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },

  // === ESCORTS ===
  {
    id: "real-009",
    name: "Society Service",
    slug: "society-service",
    city_slug: "amsterdam",
    category_slugs: ["escorts"],
    primary_category: "escorts",
    description:
      "Society Service is het bekendste high class escortbureau van Nederland, opgericht in 2006 door Marike van der Velden. Volledig legaal, vergund en belastingplichtig. De escorts zijn beschikbaar in heel Nederland met vestigingen in Amsterdam, Rotterdam, Den Haag, Utrecht en Eindhoven.",
    short_description:
      "Het bekendste high class escortbureau van Nederland, opgericht in 2006. Landelijk actief.",
    address: "Amsterdam (landelijk actief)",
    postal_code: "1017 AB",
    website: "https://www.societyservice.com",
    image_url: "/screenshots/society-service.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 4,
    is_verified: true,
    is_featured: true,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },

  // === SEKSSHOPS ===
  {
    id: "real-011",
    name: "Mister B",
    slug: "mister-b",
    city_slug: "amsterdam",
    category_slugs: ["seksshops"],
    primary_category: "seksshops",
    description:
      "Mister B is een iconische erotiekwinkel in Amsterdam-Centrum, gespecialiseerd in handgemaakt leer en fetish artikelen. Een begrip in de Nederlandse en internationale fetish-scene met een breed assortiment aan speeltjes en kleding.",
    short_description:
      "Iconische fetish- en leerwinkel in Amsterdam, een begrip in de internationale fetish-scene.",
    address: "Warmoesstraat, Amsterdam",
    postal_code: "1012 HZ",
    website: "https://www.misterb.com",
    image_url: "/screenshots/mister-b.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 3,
    is_verified: true,
    is_featured: true,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },
  {
    id: "real-012",
    name: "Pure Lust",
    slug: "pure-lust-amsterdam",
    city_slug: "amsterdam",
    category_slugs: ["seksshops"],
    primary_category: "seksshops",
    description:
      "Pure Lust is een van de meest vrouwvriendelijke erotiekwinkels van Amsterdam met vier vestigingen door de stad. Gestart aan de Oudezijds Voorburgwal en uitgegroeid tot een toonaangevende winkel voor lingerie, speeltjes en erotische accessoires.",
    short_description:
      "Vrouwvriendelijke erotiekwinkel met vier vestigingen in Amsterdam voor lingerie en speeltjes.",
    address: "Oudezijds Voorburgwal 135, Amsterdam",
    postal_code: "1012 GH",
    website: "https://purelust.com",
    image_url: "/screenshots/pure-lust-amsterdam.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 2,
    is_verified: true,
    is_featured: false,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },
  {
    id: "real-015",
    name: "Samaya Kashmiri Tantra",
    slug: "samaya-kashmiri-tantra",
    city_slug: "amsterdam",
    category_slugs: ["erotische-massage"],
    primary_category: "erotische-massage",
    description:
      "Samaya Kashmiri biedt authentieke Kashmiri tantramassage in Amsterdam. Gespecialiseerd in heilige seksualiteit en helende behandelingen. Een professionele en spirituele benadering van erotische massage met ervaren therapeuten.",
    short_description:
      "Authentieke Kashmiri tantramassage in Amsterdam, gespecialiseerd in heilende behandelingen.",
    address: "Amsterdam",
    postal_code: "1017 AB",
    website: "https://tantramassageamsterdam.nl",
    image_url: "/screenshots/samaya-kashmiri-tantra.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 3,
    is_verified: true,
    is_featured: false,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },

  // ────────────────────────────────────────────────────────────────────────────
  // ROTTERDAM
  // ────────────────────────────────────────────────────────────────────────────

  // === CLUBS / PARENCLUBS ===
  {
    id: "real-016",
    name: "Fun4Two",
    slug: "fun4two",
    city_slug: "rotterdam",
    category_slugs: ["clubs", "saunaclubs"],
    primary_category: "clubs",
    description:
      "Fun4Two in Moordrecht (bij Rotterdam) wordt door velen beschouwd als de beste swingersclub van Europa. Mensen reizen vanuit het buitenland speciaal voor een bezoek. De club biedt uitgebreide faciliteiten inclusief sauna, zwembad en themaruimtes in een luxe setting.",
    short_description:
      "Beschouwd als de beste swingersclub van Europa, gelegen bij Rotterdam in Moordrecht.",
    address: "Middelweg 18, Moordrecht (bij Rotterdam)",
    postal_code: "2841 LA",
    website: "https://www.fun4two.nl",
    image_url: "/screenshots/fun4two.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 4,
    is_verified: true,
    is_featured: true,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },

  // === STRIPCLUBS ===
  {
    id: "real-017",
    name: "BonTon Rotterdam",
    slug: "bonton-rotterdam",
    city_slug: "rotterdam",
    category_slugs: ["stripclubs"],
    primary_category: "stripclubs",
    description:
      "BonTon Rotterdam is de Rotterdamse vestiging van de luxueuze stripclubketen BonTon. Biedt dezelfde high-end ervaring als de Amsterdamse locatie met luxe settings en VIP-mogelijkheden in het centrum van Rotterdam.",
    short_description:
      "Luxe stripclub in het centrum van Rotterdam, onderdeel van de bekende BonTon-keten.",
    address: "Rotterdam Centrum",
    postal_code: "3011 AB",
    website: "https://www.stripclub-bonton.com",
    image_url: "/screenshots/bonton-rotterdam.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 4,
    is_verified: true,
    is_featured: true,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },
  {
    id: "real-019",
    name: "Cristal Prive",
    slug: "cristal-prive",
    city_slug: "rotterdam",
    category_slugs: ["privehuizen"],
    primary_category: "privehuizen",
    description:
      "Cristal Prive is een mooi privehuis centraal gelegen in Rotterdam-Zuid nabij de Maastunnel. Alle kamers zijn voorzien van een 2-persoons jacuzzi, douche en airconditioning. Dagelijks zijn er circa 10 dames aanwezig van diverse achtergronden. Gratis entree en drankjes.",
    short_description:
      "Populair privehuis in Rotterdam-Zuid met jacuzzi-kamers en gratis entree.",
    address: "Wolphaertsbocht 323B, Rotterdam",
    postal_code: "3081 KE",
    phone: "+31 10 210 8368",
    website: "https://cristalprive.nl",
    image_url: "/screenshots/cristal-prive.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 2,
    is_verified: true,
    is_featured: true,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },
  {
    id: "real-022",
    name: "IsabellaStella",
    slug: "isabellastella",
    city_slug: "rotterdam",
    category_slugs: ["erotische-massage"],
    primary_category: "erotische-massage",
    description:
      "IsabellaStella is een bekende erotische en sensuele massagesalon in het centrum van Rotterdam. Biedt professionele erotische massages in een ontspannen en luxueuze omgeving.",
    short_description:
      "Bekende erotische massagesalon in het centrum van Rotterdam met luxueuze sfeer.",
    address: "Rotterdam Centrum",
    postal_code: "3011 AB",
    website: "https://www.isabellastella.com",
    image_url: "/screenshots/isabellastella.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 3,
    is_verified: true,
    is_featured: false,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },

  // === ESCORTS ===
  {
    id: "real-023",
    name: "Hollandse Escort Service",
    slug: "hollandse-escort-service",
    city_slug: "rotterdam",
    category_slugs: ["escorts"],
    primary_category: "escorts",
    description:
      "Hollandse Escort Service is een professioneel escortbureau actief in Rotterdam, Amsterdam, Den Haag en Utrecht. Biedt discrete en professionele escorts voor diverse gelegenheden met een focus op kwaliteit en betrouwbaarheid.",
    short_description:
      "Professioneel escortbureau actief in meerdere grote steden met discrete service.",
    address: "Rotterdam (landelijk actief)",
    postal_code: "3011 AB",
    website: "https://www.hollandseescort.nl",
    image_url: "/screenshots/hollandse-escort-service.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 3,
    is_verified: true,
    is_featured: false,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },

  // ────────────────────────────────────────────────────────────────────────────
  // DEN HAAG
  // ────────────────────────────────────────────────────────────────────────────

  // === STRIPCLUBS ===
  {
    id: "real-024",
    name: "Mayfair Gentlemen's Club",
    slug: "mayfair-gentlemens-club",
    city_slug: "den-haag",
    category_slugs: ["stripclubs", "clubs"],
    primary_category: "stripclubs",
    description:
      "Mayfair Gentlemen's Club is de meest luxueuze nachtclub voor entertainment en shows in Den Haag, actief sinds 1985. Gelegen aan de Bilderdijkstraat biedt de club een verleidelijke omgeving voor ultieme ontspanning en entertainment.",
    short_description:
      "Luxueuze gentlemen's club in Den Haag sinds 1985, de bekendste van de stad.",
    address: "Bilderdijkstraat 108, Den Haag",
    postal_code: "2513 CS",
    phone: "+31 70 360 7996",
    website: "https://www.mayfair.nl",
    image_url: "/screenshots/mayfair-gentlemens-club.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 4,
    is_verified: true,
    is_featured: true,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },

  // === PRIVEHUIZEN ===
  {
    id: "real-025",
    name: "Stout Prive Huis",
    slug: "stout-prive-huis",
    city_slug: "den-haag",
    category_slugs: ["privehuizen"],
    primary_category: "privehuizen",
    description:
      "Stout Prive Huis is een exclusief privehuis in het Zeeheldenkwartier van Den Haag, geopend in 2010. Discretie, luxe en verwennerij staan centraal. Ontstaan vanuit het succes van Mayfair dat al sinds 1985 actief is.",
    short_description:
      "Exclusief privehuis in het Zeeheldenkwartier waar discretie en luxe centraal staan.",
    address: "Zeeheldenkwartier, Den Haag",
    postal_code: "2518 AB",
    website: "https://www.stoutprive.nl",
    image_url: "/screenshots/stout-prive-huis.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 3,
    is_verified: true,
    is_featured: true,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },
  {
    id: "real-032",
    name: "Velvet Elegance",
    slug: "velvet-elegance",
    city_slug: "utrecht",
    category_slugs: ["escorts"],
    primary_category: "escorts",
    description:
      "Velvet Elegance is een high class escortbureau gevestigd in Amsterdam maar actief in heel Nederland, waaronder Utrecht. Biedt verfijnde vrouwelijke begeleiding voor diverse gelegenheden.",
    short_description:
      "High class escortbureau actief in Utrecht en heel Nederland met verfijnde begeleiding.",
    address: "Utrecht (landelijk actief)",
    postal_code: "3511 AB",
    website: "https://velvetelegance.nl",
    image_url: "/screenshots/velvet-elegance.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 4,
    is_verified: true,
    is_featured: false,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },

  // ────────────────────────────────────────────────────────────────────────────
  // EINDHOVEN
  // ────────────────────────────────────────────────────────────────────────────

  // === STRIPCLUBS ===
  {
    id: "real-033",
    name: "Club Rouge",
    slug: "club-rouge",
    city_slug: "eindhoven",
    category_slugs: ["stripclubs", "clubs"],
    primary_category: "stripclubs",
    description:
      "Club Rouge is een stripclub in Eindhoven, geopend op doordeweekse avonden van 21:00-02:00 en vrijdag/zaterdag tot 04:00. Biedt entertainment en shows in een exclusieve setting.",
    short_description:
      "Stripclub in Eindhoven met entertainment en shows in een exclusieve setting.",
    address: "Eindhoven Centrum",
    postal_code: "5611 AB",
    website: "https://www.rouge-eindhoven.nl",
    image_url: "/screenshots/club-rouge.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 3,
    is_verified: true,
    is_featured: true,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },

  // === SEKSSHOPS ===
  {
    id: "real-034",
    name: "Cupido Eindhoven",
    slug: "cupido-eindhoven",
    city_slug: "eindhoven",
    category_slugs: ["seksshops"],
    primary_category: "seksshops",
    description:
      "Cupido Eindhoven is een erotiekwinkel met een breed assortiment aan erotische kleding, schoenen, lingerie, libidoversterkende producten en erotische speeltjes. Een bekende winkel voor alles op erotisch gebied in de regio Eindhoven.",
    short_description:
      "Erotiekwinkel in Eindhoven met een breed assortiment aan kleding, lingerie en speeltjes.",
    address: "Eindhoven",
    postal_code: "5611 AB",
    website: "https://cupidoeindhoven.nl",
    image_url: "/screenshots/cupido-eindhoven.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 2,
    is_verified: true,
    is_featured: false,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },

  // === CLUBS (NABIJ EINDHOVEN) ===
  {
    id: "real-036",
    name: "Gold Rianda",
    slug: "gold-rianda",
    city_slug: "groningen",
    category_slugs: ["privehuizen", "clubs", "erotische-massage"],
    primary_category: "privehuizen",
    description:
      "Gold Rianda wordt beschouwd als de beste sexclub en het beste privehuis van Groningen en Noord-Nederland. Biedt priveontvangst, erotische massage, escort en luxe VIP-wellnessruimtes met jacuzzi's. Gelegen in Nieuw Beerta.",
    short_description:
      "Beste sexclub en privehuis van Groningen en Noord-Nederland met VIP-wellness.",
    address: "Hoofdweg 73, Nieuw Beerta",
    postal_code: "9687 PK",
    website: "https://www.goldrianda.nl",
    image_url: "/screenshots/gold-rianda.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 3,
    is_verified: true,
    is_featured: true,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },
  {
    id: "real-037",
    name: "Massagesalon Groningen",
    slug: "massagesalon-groningen",
    city_slug: "groningen",
    category_slugs: ["erotische-massage"],
    primary_category: "erotische-massage",
    description:
      "Massagesalon Groningen is al tientallen jaren specialist in ontspannende en erotische massages. Een gevestigde naam in de regio Groningen voor professionele massagebehandelingen.",
    short_description:
      "Al decennia specialist in ontspannende en erotische massages in Groningen.",
    address: "Groningen",
    postal_code: "9711 AB",
    website: "https://massagesalongroningen.nl",
    image_url: "/screenshots/massagesalon-groningen.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 2,
    is_verified: true,
    is_featured: false,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },

  // ────────────────────────────────────────────────────────────────────────────
  // KLEINERE STEDEN
  // ────────────────────────────────────────────────────────────────────────────

  // === BREDA (NABIJ) ===
  {
    id: "real-038",
    name: "Parenclub Mystique",
    slug: "parenclub-mystique",
    city_slug: "breda",
    category_slugs: ["clubs"],
    primary_category: "clubs",
    description:
      "Parenclub Mystique in Rucphen (bij Breda) biedt een toegankelijke sfeer met veel faciliteiten waaronder restaurant, bar, sauna, groot bubbelbad en diverse themakamers. Geopend op vrijdag, zaterdag en zondagavond met wisselende thema-avonden.",
    short_description:
      "Toegankelijke parenclub bij Breda met sauna, bubbelbad en diverse themakamers.",
    address: "Zundertseweg 84, Rucphen",
    postal_code: "4715 SC",
    phone: "+31 165 343 280",
    website: "https://www.parenclub-mystique.nl",
    image_url: "/screenshots/parenclub-mystique.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 3,
    is_verified: true,
    is_featured: true,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },

  // === ZUNDERT (NABIJ BREDA) - SAUNACLUB ===
  {
    id: "real-039",
    name: "Saunaclub Le Grand",
    slug: "saunaclub-le-grand",
    city_slug: "breda",
    category_slugs: ["saunaclubs"],
    primary_category: "saunaclubs",
    description:
      "Saunaclub Le Grand in Zundert (bij Breda) is een bekende erotische saunaclub. Entree van 70 euro inclusief badjas, slippers, onbeperkt drinken, lopend buffet en gebruik van alle wellnessfaciliteiten. Dames werken zelfstandig.",
    short_description:
      "Bekende erotische saunaclub bij Breda met all-inclusive entree en wellnessfaciliteiten.",
    address: "Meirseweg 25, Zundert",
    postal_code: "4881 DH",
    website: "https://saunaclublegrand.nl",
    image_url: "/screenshots/saunaclub-le-grand.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 3,
    is_verified: true,
    is_featured: true,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },

  // === TILBURG ===
  {
    id: "real-040",
    name: "De Nacht",
    slug: "de-nacht",
    city_slug: "tilburg",
    category_slugs: ["stripclubs", "clubs"],
    primary_category: "stripclubs",
    description:
      "De Nacht is de enige echte nachtclub van Tilburg, gevestigd sinds 2002 aan het Heuvel in het uitgaanscentrum. Gedurende de avond verzorgen topless danseressen poledance-shows. Geopend op donderdag, vrijdag en zaterdag van 22:00 tot 06:00.",
    short_description:
      "De enige echte nachtclub van Tilburg met topless poledance-shows sinds 2002.",
    address: "Heuvel 48-A, Tilburg",
    postal_code: "5038 CL",
    website: "https://de-nacht.nl",
    image_url: "/screenshots/de-nacht.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 2,
    is_verified: true,
    is_featured: false,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },

  // === NIJMEGEN ===
  {
    id: "real-042",
    name: "Saunaclub YinYang",
    slug: "saunaclub-yinyang",
    city_slug: "maastricht",
    category_slugs: ["saunaclubs", "clubs"],
    primary_category: "saunaclubs",
    description:
      "Saunaclub YinYang in Roermond (Limburg) is een van de grootste en meest unieke clubs van Europa. Biedt drie unieke concepten onder een dak: erotiek, horeca/lounge en wellness. Dagelijks geopend van 11:00-01:00. All-in prijs vanaf 55 euro met buitensauna, zwembad, hamam en jacuzzi's.",
    short_description:
      "Een van Europa's grootste saunaclubs in Limburg met erotiek, horeca en wellness.",
    address: "Heinsbergerweg 230, Roermond",
    postal_code: "6045 CL",
    website: "https://www.yinyang.nl",
    image_url: "/screenshots/saunaclub-yinyang.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 3,
    is_verified: true,
    is_featured: true,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },

  // === BEESEL (LIMBURG) - PARENCLUB ===
  {
    id: "real-043",
    name: "Kasteel Waterloo",
    slug: "kasteel-waterloo",
    city_slug: "maastricht",
    category_slugs: ["clubs"],
    primary_category: "clubs",
    description:
      "Kasteel Waterloo in Beesel (tussen Venlo en Roermond) is de meest stijlvolle parenclub van Nederland, gevestigd in een echt kasteel. Op de begane grond restaurant, bar, dansvloer en terras. Op de bovenverdieping speelkamers en sauna. Een unieke ervaring.",
    short_description:
      "De meest stijlvolle parenclub van Nederland, gevestigd in een echt kasteel in Limburg.",
    address: "Beesel (Limburg)",
    postal_code: "5954 AB",
    website: "https://www.kasteelwaterloo.nl",
    image_url: "/screenshots/kasteel-waterloo.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 3,
    is_verified: true,
    is_featured: true,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },

  // === HEEREWAARDEN (GELDERLAND/BRABANT) - PARENCLUB ===
  {
    id: "real-044",
    name: "Parenclub Le Baron A2",
    slug: "parenclub-le-baron-a2",
    city_slug: "arnhem",
    category_slugs: ["clubs"],
    primary_category: "clubs",
    description:
      "Club Le Baron A2 is een parenclub in Heerewaarden, op de grens van Gelderland en Brabant. De club is zeven dagen per week geopend en hanteert geen dresscode. Een toegankelijke en gezellige club voor paren en singles.",
    short_description:
      "Gezellige parenclub op de grens van Gelderland en Brabant, 7 dagen per week open.",
    address: "Heerewaardensestraat 40, Heerewaarden",
    postal_code: "6624 KK",
    website: "https://www.clublebaron.nl",
    image_url: "/screenshots/parenclub-le-baron-a2.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 2,
    is_verified: true,
    is_featured: false,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },

  // === KERKRADE (LIMBURG) - PRIVEHUIS ===
  {
    id: "real-045",
    name: "Privehuis Yvonne",
    slug: "privehuis-yvonne",
    city_slug: "maastricht",
    category_slugs: ["privehuizen"],
    primary_category: "privehuizen",
    description:
      "Privehuis Yvonne in Kerkrade is het meest charmante privehuis van Limburg. Sensualiteit, passie en genot komen hier samen in een sfeervolle omgeving. Een bekende naam in Zuid-Limburg.",
    short_description:
      "Het meest charmante privehuis van Limburg in Kerkrade, bekend om sfeer en passie.",
    address: "Kerkrade, Limburg",
    postal_code: "6461 AB",
    website: "https://www.privehuisyvonne.com",
    image_url: "/screenshots/privehuis-yvonne.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 2,
    is_verified: true,
    is_featured: false,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },

  // === EXTRA ESCORTS ===
  {
    id: "real-046",
    name: "Six Stars Agency",
    slug: "six-stars-agency",
    city_slug: "amsterdam",
    category_slugs: ["escorts"],
    primary_category: "escorts",
    description:
      "Six Stars Agency is het beste hostessbureau van de Benelux met meer dan 15 jaar ervaring. Biedt high class hostesses en escorts voor evenementen, beurzen en privegelegenheden door heel Nederland.",
    short_description:
      "Beste hostessbureau van de Benelux met 15+ jaar ervaring in high class begeleiding.",
    address: "Amsterdam (landelijk actief)",
    postal_code: "1017 AB",
    website: "https://www.sixstarsagency.nl",
    image_url: "/screenshots/six-stars-agency.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 4,
    is_verified: true,
    is_featured: false,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },

  // === AMSTERDAM - EXTRA ===
  {
    id: "real-050",
    name: "Parenclub Monique",
    slug: "parenclub-monique",
    city_slug: "utrecht",
    category_slugs: ["clubs", "saunaclubs"],
    primary_category: "clubs",
    description:
      "Parenclub Monique biedt een ontspannen en gastvrije sfeer voor zowel beginners als ervaren bezoekers. Uitgebreide wellnessfaciliteiten waaronder sauna en jacuzzi, en regelmatige thema-avonden. Een van de bekendste parenclubs in de regio Utrecht.",
    short_description:
      "Gastvrije parenclub met sauna en jacuzzi, ideaal voor beginners en ervaren swingers.",
    address: "Regio Utrecht",
    postal_code: "3800 AB",
    website: "https://parenclub-monique.nl",
    image_url: "/screenshots/parenclub-monique.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 3,
    is_verified: true,
    is_featured: false,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },

  // ══════════════════════════════════════════════════════════════════════
  // ESCORT SERVICES FROM EXCEL - 68 websites
  // ══════════════════════════════════════════════════════════════════════

  {
    id: "excel-101",
    name: "He & She Escort",
    slug: "he-en-she-escort",
    city_slug: "amsterdam",
    category_slugs: ["escorts"],
    primary_category: "escorts",
    description: "He & She Escort biedt professionele en discrete escortdiensten in Amsterdam en omgeving. Betrouwbaar, punctueel en met een selectie van aantrekkelijke dames voor diverse gelegenheden.",
    short_description: "Landelijke escort service met hoge kwaliteit begeleiding.",
    address: "Amsterdam",
    postal_code: "",
    website: "https://www.he-n-she.nl",
    image_url: "/screenshots/he-en-she-escort.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 3,
    is_verified: true,
    is_featured: false,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },
  {
    id: "excel-102",
    name: "Leuke Dame",
    slug: "leuke-dame",
    city_slug: "amsterdam",
    category_slugs: ["escorts"],
    primary_category: "escorts",
    description: "Leuke Dame biedt professionele en discrete escortdiensten in Amsterdam en omgeving. Betrouwbaar, punctueel en met een selectie van aantrekkelijke dames voor diverse gelegenheden.",
    short_description: "Landelijke escort service voor de veeleisende heer.",
    address: "Amsterdam",
    postal_code: "",
    website: "https://www.leukedame.nl",
    image_url: "/screenshots/leuke-dame.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 3,
    is_verified: true,
    is_featured: false,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },
  {
    id: "excel-103",
    name: "Escort Services Leeuwarden",
    slug: "escort-services-leeuwarden",
    city_slug: "leeuwarden",
    category_slugs: ["escorts"],
    primary_category: "escorts",
    description: "Escort Services Leeuwarden biedt professionele en discrete escortdiensten in Leeuwarden en omgeving. Betrouwbaar, punctueel en met een selectie van aantrekkelijke dames voor diverse gelegenheden.",
    short_description: "Professionele escort service in Leeuwarden en omgeving.",
    address: "Leeuwarden",
    postal_code: "",
    website: "https://escort-services-friesland.nl",
    image_url: "/screenshots/escort-services-leeuwarden.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 3,
    is_verified: true,
    is_featured: false,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },
  {
    id: "excel-104",
    name: "Escort Services Groningen",
    slug: "escort-services-groningen",
    city_slug: "groningen",
    category_slugs: ["escorts"],
    primary_category: "escorts",
    description: "Escort Services Groningen biedt professionele en discrete escortdiensten in Groningen en omgeving. Betrouwbaar, punctueel en met een selectie van aantrekkelijke dames voor diverse gelegenheden.",
    short_description: "Professionele escort service in Groningen en omgeving.",
    address: "Groningen",
    postal_code: "",
    website: "https://www.escort-services-groningen.nl",
    image_url: "/screenshots/escort-services-groningen.jpg",
    average_rating: 4.0,
    review_count: 1,
    price_range: 3,
    is_verified: true,
    is_featured: false,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },
  {
    id: "excel-105",
    name: "Escort Services Assen",
    slug: "escort-services-assen",
    city_slug: "assen",
    category_slugs: ["escorts"],
    primary_category: "escorts",
    description: "Escort Services Assen biedt professionele en discrete escortdiensten in Assen en omgeving. Betrouwbaar, punctueel en met een selectie van aantrekkelijke dames voor diverse gelegenheden.",
    short_description: "Professionele escort service in Assen en omgeving.",
    address: "Assen",
    postal_code: "",
    website: "https://www.escort-services-assen.nl",
    image_url: "/screenshots/escort-services-assen.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 3,
    is_verified: true,
    is_featured: false,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },
  {
    id: "excel-106",
    name: "Escort Services Zwolle",
    slug: "escort-services-zwolle",
    city_slug: "zwolle",
    category_slugs: ["escorts"],
    primary_category: "escorts",
    description: "Escort Services Zwolle biedt professionele en discrete escortdiensten in Zwolle en omgeving. Betrouwbaar, punctueel en met een selectie van aantrekkelijke dames voor diverse gelegenheden.",
    short_description: "Professionele escort service in Zwolle en omgeving.",
    address: "Zwolle",
    postal_code: "",
    website: "https://escort-services-zwolle.nl",
    image_url: "/screenshots/escort-services-zwolle.jpg",
    average_rating: 4.0,
    review_count: 1,
    price_range: 3,
    is_verified: true,
    is_featured: false,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },
  {
    id: "excel-107",
    name: "Escort Services Enschede",
    slug: "escort-services-enschede",
    city_slug: "enschede",
    category_slugs: ["escorts"],
    primary_category: "escorts",
    description: "Escort Services Enschede biedt professionele en discrete escortdiensten in Enschede en omgeving. Betrouwbaar, punctueel en met een selectie van aantrekkelijke dames voor diverse gelegenheden.",
    short_description: "Professionele escort service in Enschede en omgeving.",
    address: "Enschede",
    postal_code: "",
    website: "https://www.escort-services-enschede.nl",
    image_url: "/screenshots/escort-services-enschede.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 3,
    is_verified: true,
    is_featured: false,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },
  {
    id: "excel-108",
    name: "Escort Services Arnhem",
    slug: "escort-services-arnhem",
    city_slug: "arnhem",
    category_slugs: ["escorts"],
    primary_category: "escorts",
    description: "Escort Services Arnhem biedt professionele en discrete escortdiensten in Arnhem en omgeving. Betrouwbaar, punctueel en met een selectie van aantrekkelijke dames voor diverse gelegenheden.",
    short_description: "Professionele escort service in Arnhem en omgeving.",
    address: "Arnhem",
    postal_code: "",
    website: "https://www.escort-services-arnhem.nl",
    image_url: "/screenshots/escort-services-arnhem.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 3,
    is_verified: true,
    is_featured: false,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },
  {
    id: "excel-109",
    name: "Escort Services Apeldoorn",
    slug: "escort-services-apeldoorn",
    city_slug: "apeldoorn",
    category_slugs: ["escorts"],
    primary_category: "escorts",
    description: "Escort Services Apeldoorn biedt professionele en discrete escortdiensten in Apeldoorn en omgeving. Betrouwbaar, punctueel en met een selectie van aantrekkelijke dames voor diverse gelegenheden.",
    short_description: "Professionele escort service in Apeldoorn en omgeving.",
    address: "Apeldoorn",
    postal_code: "",
    website: "https://www.escort-services-apeldoorn.nl",
    image_url: "/screenshots/escort-services-apeldoorn.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 3,
    is_verified: true,
    is_featured: false,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },
  {
    id: "excel-110",
    name: "Escort Services Nijmegen",
    slug: "escort-services-nijmegen",
    city_slug: "nijmegen",
    category_slugs: ["escorts"],
    primary_category: "escorts",
    description: "Escort Services Nijmegen biedt professionele en discrete escortdiensten in Nijmegen en omgeving. Betrouwbaar, punctueel en met een selectie van aantrekkelijke dames voor diverse gelegenheden.",
    short_description: "Professionele escort service in Nijmegen en omgeving.",
    address: "Nijmegen",
    postal_code: "",
    website: "https://www.escort-services-nijmegen.nl",
    image_url: "/screenshots/escort-services-nijmegen.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 3,
    is_verified: true,
    is_featured: false,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },
  {
    id: "excel-111",
    name: "Escort Services Almere",
    slug: "escort-services-almere",
    city_slug: "almere",
    category_slugs: ["escorts"],
    primary_category: "escorts",
    description: "Escort Services Almere biedt professionele en discrete escortdiensten in Almere en omgeving. Betrouwbaar, punctueel en met een selectie van aantrekkelijke dames voor diverse gelegenheden.",
    short_description: "Professionele escort service in Almere en omgeving.",
    address: "Almere",
    postal_code: "",
    website: "https://www.escort-services-almere.nl",
    image_url: "/screenshots/escort-services-almere.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 3,
    is_verified: true,
    is_featured: false,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },
  {
    id: "excel-112",
    name: "Escort Services Utrecht",
    slug: "escort-services-utrecht",
    city_slug: "utrecht",
    category_slugs: ["escorts"],
    primary_category: "escorts",
    description: "Escort Services Utrecht biedt professionele en discrete escortdiensten in Utrecht en omgeving. Betrouwbaar, punctueel en met een selectie van aantrekkelijke dames voor diverse gelegenheden.",
    short_description: "Professionele escort service in Utrecht en omgeving.",
    address: "Utrecht",
    postal_code: "",
    website: "https://www.escort-services-utrecht.nl",
    image_url: "/screenshots/escort-services-utrecht.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 3,
    is_verified: true,
    is_featured: false,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },
  {
    id: "excel-113",
    name: "Escort Services Amersfoort",
    slug: "escort-services-amersfoort",
    city_slug: "amersfoort",
    category_slugs: ["escorts"],
    primary_category: "escorts",
    description: "Escort Services Amersfoort biedt professionele en discrete escortdiensten in Amersfoort en omgeving. Betrouwbaar, punctueel en met een selectie van aantrekkelijke dames voor diverse gelegenheden.",
    short_description: "Professionele escort service in Amersfoort en omgeving.",
    address: "Amersfoort",
    postal_code: "",
    website: "https://www.escort-services-amersfoort.nl",
    image_url: "/screenshots/escort-services-amersfoort.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 3,
    is_verified: true,
    is_featured: false,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },
  {
    id: "excel-114",
    name: "Escort Services Maastricht",
    slug: "escort-services-maastricht",
    city_slug: "maastricht",
    category_slugs: ["escorts"],
    primary_category: "escorts",
    description: "Escort Services Maastricht biedt professionele en discrete escortdiensten in Maastricht en omgeving. Betrouwbaar, punctueel en met een selectie van aantrekkelijke dames voor diverse gelegenheden.",
    short_description: "Professionele escort service in Maastricht en omgeving.",
    address: "Maastricht",
    postal_code: "",
    website: "https://www.escort-services-maastricht.nl",
    image_url: "/screenshots/escort-services-maastricht.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 3,
    is_verified: true,
    is_featured: false,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },
  {
    id: "excel-115",
    name: "Escort Services Sittard-Geleen",
    slug: "escort-services-sittard-geleen",
    city_slug: "sittard-geleen",
    category_slugs: ["escorts"],
    primary_category: "escorts",
    description: "Escort Services Sittard-Geleen biedt professionele en discrete escortdiensten in Sittard-Geleen en omgeving. Betrouwbaar, punctueel en met een selectie van aantrekkelijke dames voor diverse gelegenheden.",
    short_description: "Professionele escort service in Sittard-Geleen en omgeving.",
    address: "Sittard-Geleen",
    postal_code: "",
    website: "https://escort-services-sittard.nl",
    image_url: "/screenshots/escort-services-sittard-geleen.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 3,
    is_verified: true,
    is_featured: false,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },
  {
    id: "excel-116",
    name: "Escort Services Roermond",
    slug: "escort-services-roermond",
    city_slug: "roermond",
    category_slugs: ["escorts"],
    primary_category: "escorts",
    description: "Escort Services Roermond biedt professionele en discrete escortdiensten in Roermond en omgeving. Betrouwbaar, punctueel en met een selectie van aantrekkelijke dames voor diverse gelegenheden.",
    short_description: "Professionele escort service in Roermond en omgeving.",
    address: "Roermond",
    postal_code: "",
    website: "https://www.escort-services-roermond.nl",
    image_url: "/screenshots/escort-services-roermond.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 3,
    is_verified: true,
    is_featured: false,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },
  {
    id: "excel-117",
    name: "Escort Services Weert",
    slug: "escort-services-weert",
    city_slug: "weert",
    category_slugs: ["escorts"],
    primary_category: "escorts",
    description: "Escort Services Weert biedt professionele en discrete escortdiensten in Weert en omgeving. Betrouwbaar, punctueel en met een selectie van aantrekkelijke dames voor diverse gelegenheden.",
    short_description: "Professionele escort service in Weert en omgeving.",
    address: "Weert",
    postal_code: "",
    website: "https://escort-services-weert.nl",
    image_url: "/screenshots/escort-services-weert.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 3,
    is_verified: true,
    is_featured: false,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },
  {
    id: "excel-118",
    name: "Escort Services 's-Hertogenbosch",
    slug: "escort-services-s-hertogenbosch",
    city_slug: "s-hertogenbosch",
    category_slugs: ["escorts"],
    primary_category: "escorts",
    description: "Escort Services 's-Hertogenbosch biedt professionele en discrete escortdiensten in 's-Hertogenbosch en omgeving. Betrouwbaar, punctueel en met een selectie van aantrekkelijke dames voor diverse gelegenheden.",
    short_description: "Professionele escort service in 's-Hertogenbosch en omgeving.",
    address: "'s-Hertogenbosch",
    postal_code: "",
    website: "https://www.escort-services-denbosch.nl",
    image_url: "/screenshots/escort-services-s-hertogenbosch.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 3,
    is_verified: true,
    is_featured: false,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },
  {
    id: "excel-119",
    name: "Escort Services Eindhoven",
    slug: "escort-services-eindhoven",
    city_slug: "eindhoven",
    category_slugs: ["escorts"],
    primary_category: "escorts",
    description: "Escort Services Eindhoven biedt professionele en discrete escortdiensten in Eindhoven en omgeving. Betrouwbaar, punctueel en met een selectie van aantrekkelijke dames voor diverse gelegenheden.",
    short_description: "Professionele escort service in Eindhoven en omgeving.",
    address: "Eindhoven",
    postal_code: "",
    website: "https://www.escort-services-eindhoven.nl",
    image_url: "/screenshots/escort-services-eindhoven.jpg",
    average_rating: 5.0,
    review_count: 1,
    price_range: 3,
    is_verified: true,
    is_featured: false,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },
  {
    id: "excel-120",
    name: "Escort Services Tilburg",
    slug: "escort-services-tilburg",
    city_slug: "tilburg",
    category_slugs: ["escorts"],
    primary_category: "escorts",
    description: "Escort Services Tilburg biedt professionele en discrete escortdiensten in Tilburg en omgeving. Betrouwbaar, punctueel en met een selectie van aantrekkelijke dames voor diverse gelegenheden.",
    short_description: "Professionele escort service in Tilburg en omgeving.",
    address: "Tilburg",
    postal_code: "",
    website: "https://escort-services-tilburg.nl",
    image_url: "/screenshots/escort-services-tilburg.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 3,
    is_verified: true,
    is_featured: false,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },
  {
    id: "excel-121",
    name: "Escort Services Breda",
    slug: "escort-services-breda",
    city_slug: "breda",
    category_slugs: ["escorts"],
    primary_category: "escorts",
    description: "Escort Services Breda biedt professionele en discrete escortdiensten in Breda en omgeving. Betrouwbaar, punctueel en met een selectie van aantrekkelijke dames voor diverse gelegenheden.",
    short_description: "Professionele escort service in Breda en omgeving.",
    address: "Breda",
    postal_code: "",
    website: "https://escort-services-breda.nl",
    image_url: "/screenshots/escort-services-breda.jpg",
    average_rating: 5.0,
    review_count: 2,
    price_range: 3,
    is_verified: true,
    is_featured: false,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },
  {
    id: "excel-122",
    name: "Escort Services Roosendaal",
    slug: "escort-services-roosendaal",
    city_slug: "roosendaal",
    category_slugs: ["escorts"],
    primary_category: "escorts",
    description: "Escort Services Roosendaal biedt professionele en discrete escortdiensten in Roosendaal en omgeving. Betrouwbaar, punctueel en met een selectie van aantrekkelijke dames voor diverse gelegenheden.",
    short_description: "Professionele escort service in Roosendaal en omgeving.",
    address: "Roosendaal",
    postal_code: "",
    website: "https://escort-services-roosendaal.nl",
    image_url: "/screenshots/escort-services-roosendaal.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 3,
    is_verified: true,
    is_featured: false,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },
  {
    id: "excel-123",
    name: "Escort Services Helmond",
    slug: "escort-services-helmond",
    city_slug: "helmond",
    category_slugs: ["escorts"],
    primary_category: "escorts",
    description: "Escort Services Helmond biedt professionele en discrete escortdiensten in Helmond en omgeving. Betrouwbaar, punctueel en met een selectie van aantrekkelijke dames voor diverse gelegenheden.",
    short_description: "Professionele escort service in Helmond en omgeving.",
    address: "Helmond",
    postal_code: "",
    website: "https://escort-services-helmond.nl",
    image_url: "/screenshots/escort-services-helmond.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 3,
    is_verified: true,
    is_featured: false,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },
  {
    id: "excel-124",
    name: "Escort Services Uden",
    slug: "escort-services-uden",
    city_slug: "uden",
    category_slugs: ["escorts"],
    primary_category: "escorts",
    description: "Escort Services Uden biedt professionele en discrete escortdiensten in Uden en omgeving. Betrouwbaar, punctueel en met een selectie van aantrekkelijke dames voor diverse gelegenheden.",
    short_description: "Professionele escort service in Uden en omgeving.",
    address: "Uden",
    postal_code: "",
    website: "https://escort-services-uden.nl",
    image_url: "/screenshots/escort-services-uden.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 3,
    is_verified: true,
    is_featured: false,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },
  {
    id: "excel-125",
    name: "Escort Services Veghel",
    slug: "escort-services-veghel",
    city_slug: "veghel",
    category_slugs: ["escorts"],
    primary_category: "escorts",
    description: "Escort Services Veghel biedt professionele en discrete escortdiensten in Veghel en omgeving. Betrouwbaar, punctueel en met een selectie van aantrekkelijke dames voor diverse gelegenheden.",
    short_description: "Professionele escort service in Veghel en omgeving.",
    address: "Veghel",
    postal_code: "",
    website: "https://escort-services-veghel.nl",
    image_url: "/screenshots/escort-services-veghel.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 3,
    is_verified: true,
    is_featured: false,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },
  {
    id: "excel-126",
    name: "Escort Services Middelburg",
    slug: "escort-services-middelburg",
    city_slug: "middelburg",
    category_slugs: ["escorts"],
    primary_category: "escorts",
    description: "Escort Services Middelburg biedt professionele en discrete escortdiensten in Middelburg en omgeving. Betrouwbaar, punctueel en met een selectie van aantrekkelijke dames voor diverse gelegenheden.",
    short_description: "Professionele escort service in Middelburg en omgeving.",
    address: "Middelburg",
    postal_code: "",
    website: "https://www.escort-services-middelburg.nl",
    image_url: "/screenshots/escort-services-middelburg.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 3,
    is_verified: true,
    is_featured: false,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },
  {
    id: "excel-127",
    name: "Escort Services Rotterdam",
    slug: "escort-services-rotterdam",
    city_slug: "rotterdam",
    category_slugs: ["escorts"],
    primary_category: "escorts",
    description: "Escort Services Rotterdam biedt professionele en discrete escortdiensten in Rotterdam en omgeving. Betrouwbaar, punctueel en met een selectie van aantrekkelijke dames voor diverse gelegenheden.",
    short_description: "Professionele escort service in Rotterdam en omgeving.",
    address: "Rotterdam",
    postal_code: "",
    website: "https://escort-services-rotterdam.nl",
    image_url: "/screenshots/escort-services-rotterdam.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 3,
    is_verified: true,
    is_featured: false,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },
  {
    id: "excel-128",
    name: "Escort Services Den Haag",
    slug: "escort-services-den-haag",
    city_slug: "den-haag",
    category_slugs: ["escorts"],
    primary_category: "escorts",
    description: "Escort Services Den Haag biedt professionele en discrete escortdiensten in Den Haag en omgeving. Betrouwbaar, punctueel en met een selectie van aantrekkelijke dames voor diverse gelegenheden.",
    short_description: "Professionele escort service in Den Haag en omgeving.",
    address: "Den Haag",
    postal_code: "",
    website: "https://www.escort-services-denhaag.nl",
    image_url: "/screenshots/escort-services-den-haag.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 3,
    is_verified: true,
    is_featured: false,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },
  {
    id: "excel-129",
    name: "Escort Services Dordrecht",
    slug: "escort-services-dordrecht",
    city_slug: "dordrecht",
    category_slugs: ["escorts"],
    primary_category: "escorts",
    description: "Escort Services Dordrecht biedt professionele en discrete escortdiensten in Dordrecht en omgeving. Betrouwbaar, punctueel en met een selectie van aantrekkelijke dames voor diverse gelegenheden.",
    short_description: "Professionele escort service in Dordrecht en omgeving.",
    address: "Dordrecht",
    postal_code: "",
    website: "https://escort-services-dordrecht.nl",
    image_url: "/screenshots/escort-services-dordrecht.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 3,
    is_verified: true,
    is_featured: false,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },
  {
    id: "excel-130",
    name: "Escort Services Leiden",
    slug: "escort-services-leiden",
    city_slug: "leiden",
    category_slugs: ["escorts"],
    primary_category: "escorts",
    description: "Escort Services Leiden biedt professionele en discrete escortdiensten in Leiden en omgeving. Betrouwbaar, punctueel en met een selectie van aantrekkelijke dames voor diverse gelegenheden.",
    short_description: "Professionele escort service in Leiden en omgeving.",
    address: "Leiden",
    postal_code: "",
    website: "https://www.escort-services-leiden.nl",
    image_url: "/screenshots/escort-services-leiden.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 3,
    is_verified: true,
    is_featured: false,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },
  {
    id: "excel-131",
    name: "Escort Services Amsterdam",
    slug: "escort-services-amsterdam",
    city_slug: "amsterdam",
    category_slugs: ["escorts"],
    primary_category: "escorts",
    description: "Escort Services Amsterdam biedt professionele en discrete escortdiensten in Amsterdam en omgeving. Betrouwbaar, punctueel en met een selectie van aantrekkelijke dames voor diverse gelegenheden.",
    short_description: "Professionele escort service in Amsterdam en omgeving.",
    address: "Amsterdam",
    postal_code: "",
    website: "https://www.escort-services-amsterdam.nl",
    image_url: "/screenshots/escort-services-amsterdam.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 3,
    is_verified: true,
    is_featured: false,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },
  {
    id: "excel-132",
    name: "Escort Service Breda",
    slug: "escort-service-breda",
    city_slug: "breda",
    category_slugs: ["escorts"],
    primary_category: "escorts",
    description: "Escort Service Breda biedt professionele en discrete escortdiensten in Breda en omgeving. Betrouwbaar, punctueel en met een selectie van aantrekkelijke dames voor diverse gelegenheden.",
    short_description: "Betrouwbare escort service in Breda en omstreken.",
    address: "Breda",
    postal_code: "",
    website: "https://www.escortservicebreda.nl",
    image_url: "/screenshots/escort-service-breda.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 3,
    is_verified: true,
    is_featured: false,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },
  {
    id: "excel-133",
    name: "Escort Service Helmond",
    slug: "escort-service-helmond",
    city_slug: "helmond",
    category_slugs: ["escorts"],
    primary_category: "escorts",
    description: "Escort Service Helmond biedt professionele en discrete escortdiensten in Helmond en omgeving. Betrouwbaar, punctueel en met een selectie van aantrekkelijke dames voor diverse gelegenheden.",
    short_description: "Betrouwbare escort service in Helmond en omstreken.",
    address: "Helmond",
    postal_code: "",
    website: "https://www.escortservicehelmond.nl",
    image_url: "/screenshots/escort-service-helmond.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 3,
    is_verified: true,
    is_featured: false,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },
  {
    id: "excel-134",
    name: "Escort Service Venlo",
    slug: "escort-service-venlo",
    city_slug: "venlo",
    category_slugs: ["escorts"],
    primary_category: "escorts",
    description: "Escort Service Venlo biedt professionele en discrete escortdiensten in Venlo en omgeving. Betrouwbaar, punctueel en met een selectie van aantrekkelijke dames voor diverse gelegenheden.",
    short_description: "Betrouwbare escort service in Venlo en omstreken.",
    address: "Venlo",
    postal_code: "",
    website: "https://www.escortservice-venlo.nl",
    image_url: "/screenshots/escort-service-venlo.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 3,
    is_verified: true,
    is_featured: false,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },
  {
    id: "excel-135",
    name: "Escort Service Groningen",
    slug: "escort-service-groningen",
    city_slug: "groningen",
    category_slugs: ["escorts"],
    primary_category: "escorts",
    description: "Escort Service Groningen biedt professionele en discrete escortdiensten in Groningen en omgeving. Betrouwbaar, punctueel en met een selectie van aantrekkelijke dames voor diverse gelegenheden.",
    short_description: "Betrouwbare escort service in Groningen en omstreken.",
    address: "Groningen",
    postal_code: "",
    website: "https://www.escort-service-groningen.nl",
    image_url: "/screenshots/escort-service-groningen.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 3,
    is_verified: true,
    is_featured: false,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },
  {
    id: "excel-136",
    name: "Escort Assen",
    slug: "escort-assen",
    city_slug: "assen",
    category_slugs: ["escorts"],
    primary_category: "escorts",
    description: "Escort Assen biedt professionele en discrete escortdiensten in Assen en omgeving. Betrouwbaar, punctueel en met een selectie van aantrekkelijke dames voor diverse gelegenheden.",
    short_description: "Escort service in Assen en omgeving.",
    address: "Assen",
    postal_code: "",
    website: "https://www.escortassen.nl",
    image_url: "/screenshots/escort-assen.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 3,
    is_verified: true,
    is_featured: false,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },
  {
    id: "excel-137",
    name: "Escort Service Zwolle",
    slug: "escort-service-zwolle",
    city_slug: "zwolle",
    category_slugs: ["escorts"],
    primary_category: "escorts",
    description: "Escort Service Zwolle biedt professionele en discrete escortdiensten in Zwolle en omgeving. Betrouwbaar, punctueel en met een selectie van aantrekkelijke dames voor diverse gelegenheden.",
    short_description: "Betrouwbare escort service in Zwolle en omstreken.",
    address: "Zwolle",
    postal_code: "",
    website: "https://www.escort-service-zwolle.nl",
    image_url: "/screenshots/escort-service-zwolle.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 3,
    is_verified: true,
    is_featured: false,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },
  {
    id: "excel-138",
    name: "Escort Service Enschede",
    slug: "escort-service-enschede",
    city_slug: "enschede",
    category_slugs: ["escorts"],
    primary_category: "escorts",
    description: "Escort Service Enschede biedt professionele en discrete escortdiensten in Enschede en omgeving. Betrouwbaar, punctueel en met een selectie van aantrekkelijke dames voor diverse gelegenheden.",
    short_description: "Betrouwbare escort service in Enschede en omstreken.",
    address: "Enschede",
    postal_code: "",
    website: "https://www.escort-service-enschede.nl",
    image_url: "/screenshots/escort-service-enschede.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 3,
    is_verified: true,
    is_featured: false,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },
  {
    id: "excel-139",
    name: "Escort Service Apeldoorn",
    slug: "escort-service-apeldoorn",
    city_slug: "apeldoorn",
    category_slugs: ["escorts"],
    primary_category: "escorts",
    description: "Escort Service Apeldoorn biedt professionele en discrete escortdiensten in Apeldoorn en omgeving. Betrouwbaar, punctueel en met een selectie van aantrekkelijke dames voor diverse gelegenheden.",
    short_description: "Betrouwbare escort service in Apeldoorn en omstreken.",
    address: "Apeldoorn",
    postal_code: "",
    website: "https://www.escort-service-apeldoorn.nl",
    image_url: "/screenshots/escort-service-apeldoorn.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 3,
    is_verified: true,
    is_featured: false,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },
  {
    id: "excel-140",
    name: "Escort Service Nijmegen",
    slug: "escort-service-nijmegen",
    city_slug: "nijmegen",
    category_slugs: ["escorts"],
    primary_category: "escorts",
    description: "Escort Service Nijmegen biedt professionele en discrete escortdiensten in Nijmegen en omgeving. Betrouwbaar, punctueel en met een selectie van aantrekkelijke dames voor diverse gelegenheden.",
    short_description: "Betrouwbare escort service in Nijmegen en omstreken.",
    address: "Nijmegen",
    postal_code: "",
    website: "https://www.escort-service-nijmegen.nl",
    image_url: "/screenshots/escort-service-nijmegen.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 3,
    is_verified: true,
    is_featured: false,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },
  {
    id: "excel-141",
    name: "Escort Service Arnhem",
    slug: "escort-service-arnhem",
    city_slug: "arnhem",
    category_slugs: ["escorts"],
    primary_category: "escorts",
    description: "Escort Service Arnhem biedt professionele en discrete escortdiensten in Arnhem en omgeving. Betrouwbaar, punctueel en met een selectie van aantrekkelijke dames voor diverse gelegenheden.",
    short_description: "Betrouwbare escort service in Arnhem en omstreken.",
    address: "Arnhem",
    postal_code: "",
    website: "https://www.escort-service-arnhem.nl",
    image_url: "/screenshots/escort-service-arnhem.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 3,
    is_verified: true,
    is_featured: false,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },
  {
    id: "excel-142",
    name: "Escort Service Utrecht",
    slug: "escort-service-utrecht",
    city_slug: "utrecht",
    category_slugs: ["escorts"],
    primary_category: "escorts",
    description: "Escort Service Utrecht biedt professionele en discrete escortdiensten in Utrecht en omgeving. Betrouwbaar, punctueel en met een selectie van aantrekkelijke dames voor diverse gelegenheden.",
    short_description: "Betrouwbare escort service in Utrecht en omstreken.",
    address: "Utrecht",
    postal_code: "",
    website: "https://www.escort-service-utrecht.nl",
    image_url: "/screenshots/escort-service-utrecht.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 3,
    is_verified: true,
    is_featured: false,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },
  {
    id: "excel-143",
    name: "Escort Service Weert",
    slug: "escort-service-weert",
    city_slug: "weert",
    category_slugs: ["escorts"],
    primary_category: "escorts",
    description: "Escort Service Weert biedt professionele en discrete escortdiensten in Weert en omgeving. Betrouwbaar, punctueel en met een selectie van aantrekkelijke dames voor diverse gelegenheden.",
    short_description: "Betrouwbare escort service in Weert en omstreken.",
    address: "Weert",
    postal_code: "",
    website: "https://www.escort-service-weert.nl",
    image_url: "/screenshots/escort-service-weert.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 3,
    is_verified: true,
    is_featured: false,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },
  {
    id: "excel-144",
    name: "Escort Service Maastricht",
    slug: "escort-service-maastricht",
    city_slug: "maastricht",
    category_slugs: ["escorts"],
    primary_category: "escorts",
    description: "Escort Service Maastricht biedt professionele en discrete escortdiensten in Maastricht en omgeving. Betrouwbaar, punctueel en met een selectie van aantrekkelijke dames voor diverse gelegenheden.",
    short_description: "Betrouwbare escort service in Maastricht en omstreken.",
    address: "Maastricht",
    postal_code: "",
    website: "https://www.escort-service-maastricht.nl",
    image_url: "/screenshots/escort-service-maastricht.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 3,
    is_verified: true,
    is_featured: false,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },
  {
    id: "excel-145",
    name: "Escort Service Sittard-Geleen",
    slug: "escort-service-sittard-geleen",
    city_slug: "sittard-geleen",
    category_slugs: ["escorts"],
    primary_category: "escorts",
    description: "Escort Service Sittard-Geleen biedt professionele en discrete escortdiensten in Sittard-Geleen en omgeving. Betrouwbaar, punctueel en met een selectie van aantrekkelijke dames voor diverse gelegenheden.",
    short_description: "Betrouwbare escort service in Sittard-Geleen en omstreken.",
    address: "Sittard-Geleen",
    postal_code: "",
    website: "https://www.escort-service-sittard.nl",
    image_url: "/screenshots/escort-service-sittard-geleen.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 3,
    is_verified: true,
    is_featured: false,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },
  {
    id: "excel-146",
    name: "Escort Service Venlo",
    slug: "escort-service-venlo",
    city_slug: "venlo",
    category_slugs: ["escorts"],
    primary_category: "escorts",
    description: "Escort Service Venlo biedt professionele en discrete escortdiensten in Venlo en omgeving. Betrouwbaar, punctueel en met een selectie van aantrekkelijke dames voor diverse gelegenheden.",
    short_description: "Betrouwbare escort service in Venlo en omstreken.",
    address: "Venlo",
    postal_code: "",
    website: "https://www.escort-service-venlo.nl",
    image_url: "/screenshots/escort-service-venlo.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 3,
    is_verified: true,
    is_featured: false,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },
  {
    id: "excel-147",
    name: "Escort Service Roermond",
    slug: "escort-service-roermond",
    city_slug: "roermond",
    category_slugs: ["escorts"],
    primary_category: "escorts",
    description: "Escort Service Roermond biedt professionele en discrete escortdiensten in Roermond en omgeving. Betrouwbaar, punctueel en met een selectie van aantrekkelijke dames voor diverse gelegenheden.",
    short_description: "Betrouwbare escort service in Roermond en omstreken.",
    address: "Roermond",
    postal_code: "",
    website: "https://www.escort-service-roermond.nl",
    image_url: "/screenshots/escort-service-roermond.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 3,
    is_verified: true,
    is_featured: false,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },
  {
    id: "excel-148",
    name: "Escort Service Breda",
    slug: "escort-service-breda",
    city_slug: "breda",
    category_slugs: ["escorts"],
    primary_category: "escorts",
    description: "Escort Service Breda biedt professionele en discrete escortdiensten in Breda en omgeving. Betrouwbaar, punctueel en met een selectie van aantrekkelijke dames voor diverse gelegenheden.",
    short_description: "Betrouwbare escort service in Breda en omstreken.",
    address: "Breda",
    postal_code: "",
    website: "https://www.escort-service-breda.nl",
    image_url: "/screenshots/escort-service-breda.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 3,
    is_verified: true,
    is_featured: false,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },
  {
    id: "excel-149",
    name: "Escort Service Helmond",
    slug: "escort-service-helmond",
    city_slug: "helmond",
    category_slugs: ["escorts"],
    primary_category: "escorts",
    description: "Escort Service Helmond biedt professionele en discrete escortdiensten in Helmond en omgeving. Betrouwbaar, punctueel en met een selectie van aantrekkelijke dames voor diverse gelegenheden.",
    short_description: "Betrouwbare escort service in Helmond en omstreken.",
    address: "Helmond",
    postal_code: "",
    website: "https://www.escort-service-helmond.nl",
    image_url: "/screenshots/escort-service-helmond.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 3,
    is_verified: true,
    is_featured: false,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },
  {
    id: "excel-150",
    name: "Escort Service Eindhoven",
    slug: "escort-service-eindhoven",
    city_slug: "eindhoven",
    category_slugs: ["escorts"],
    primary_category: "escorts",
    description: "Escort Service Eindhoven biedt professionele en discrete escortdiensten in Eindhoven en omgeving. Betrouwbaar, punctueel en met een selectie van aantrekkelijke dames voor diverse gelegenheden.",
    short_description: "Betrouwbare escort service in Eindhoven en omstreken.",
    address: "Eindhoven",
    postal_code: "",
    website: "https://www.escort-service-eindhoven.nl",
    image_url: "/screenshots/escort-service-eindhoven.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 3,
    is_verified: true,
    is_featured: false,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },
  {
    id: "excel-151",
    name: "Escort Service Tilburg",
    slug: "escort-service-tilburg",
    city_slug: "tilburg",
    category_slugs: ["escorts"],
    primary_category: "escorts",
    description: "Escort Service Tilburg biedt professionele en discrete escortdiensten in Tilburg en omgeving. Betrouwbaar, punctueel en met een selectie van aantrekkelijke dames voor diverse gelegenheden.",
    short_description: "Betrouwbare escort service in Tilburg en omstreken.",
    address: "Tilburg",
    postal_code: "",
    website: "https://www.escort-service-tilburg.nl",
    image_url: "/screenshots/escort-service-tilburg.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 3,
    is_verified: true,
    is_featured: false,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },
  {
    id: "excel-152",
    name: "Escort Service 's-Hertogenbosch",
    slug: "escort-service-s-hertogenbosch",
    city_slug: "s-hertogenbosch",
    category_slugs: ["escorts"],
    primary_category: "escorts",
    description: "Escort Service 's-Hertogenbosch biedt professionele en discrete escortdiensten in 's-Hertogenbosch en omgeving. Betrouwbaar, punctueel en met een selectie van aantrekkelijke dames voor diverse gelegenheden.",
    short_description: "Betrouwbare escort service in 's-Hertogenbosch en omstreken.",
    address: "'s-Hertogenbosch",
    postal_code: "",
    website: "https://www.escort-service-denbosch.nl",
    image_url: "/screenshots/escort-service-s-hertogenbosch.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 3,
    is_verified: true,
    is_featured: false,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },
  {
    id: "excel-153",
    name: "Escort Middelburg",
    slug: "escort-middelburg",
    city_slug: "middelburg",
    category_slugs: ["escorts"],
    primary_category: "escorts",
    description: "Escort Middelburg biedt professionele en discrete escortdiensten in Middelburg en omgeving. Betrouwbaar, punctueel en met een selectie van aantrekkelijke dames voor diverse gelegenheden.",
    short_description: "Escort service in Middelburg en heel Zeeland.",
    address: "Middelburg",
    postal_code: "",
    website: "https://www.escortmiddelburg.nl",
    image_url: "/screenshots/escort-middelburg.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 3,
    is_verified: true,
    is_featured: false,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },
  {
    id: "excel-154",
    name: "Escort Service Rotterdam",
    slug: "escort-service-rotterdam",
    city_slug: "rotterdam",
    category_slugs: ["escorts"],
    primary_category: "escorts",
    description: "Escort Service Rotterdam biedt professionele en discrete escortdiensten in Rotterdam en omgeving. Betrouwbaar, punctueel en met een selectie van aantrekkelijke dames voor diverse gelegenheden.",
    short_description: "Betrouwbare escort service in Rotterdam en omstreken.",
    address: "Rotterdam",
    postal_code: "",
    website: "https://www.escort-service-rotterdam.nl",
    image_url: "/screenshots/escort-service-rotterdam.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 3,
    is_verified: true,
    is_featured: false,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },
  {
    id: "excel-155",
    name: "Escort Service Amsterdam",
    slug: "escort-service-amsterdam",
    city_slug: "amsterdam",
    category_slugs: ["escorts"],
    primary_category: "escorts",
    description: "Escort Service Amsterdam biedt professionele en discrete escortdiensten in Amsterdam en omgeving. Betrouwbaar, punctueel en met een selectie van aantrekkelijke dames voor diverse gelegenheden.",
    short_description: "Betrouwbare escort service in Amsterdam en omstreken.",
    address: "Amsterdam",
    postal_code: "",
    website: "https://www.escort-service-amsterdam.nl",
    image_url: "/screenshots/escort-service-amsterdam.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 3,
    is_verified: true,
    is_featured: false,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },
  {
    id: "excel-156",
    name: "Escort Service Schiphol/Haarlemmermeer",
    slug: "escort-service-schiphol/haarlemmermeer",
    city_slug: "haarlemmermeer",
    category_slugs: ["escorts"],
    primary_category: "escorts",
    description: "Escort Service Schiphol/Haarlemmermeer biedt professionele en discrete escortdiensten in Schiphol/Haarlemmermeer en omgeving. Betrouwbaar, punctueel en met een selectie van aantrekkelijke dames voor diverse gelegenheden.",
    short_description: "Betrouwbare escort service in Schiphol/Haarlemmermeer en omstreken.",
    address: "Schiphol/Haarlemmermeer",
    postal_code: "",
    website: "https://www.escort-service-schiphol.nl",
    image_url: "/screenshots/escort-service-schiphol/haarlemmermeer.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 3,
    is_verified: true,
    is_featured: false,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },
  {
    id: "excel-157",
    name: "Happy Escort Zeeland",
    slug: "happy-escort-zeeland",
    city_slug: "middelburg",
    category_slugs: ["escorts"],
    primary_category: "escorts",
    description: "Happy Escort Zeeland biedt professionele en discrete escortdiensten in Middelburg en omgeving. Betrouwbaar, punctueel en met een selectie van aantrekkelijke dames voor diverse gelegenheden.",
    short_description: "Escort service actief in heel Zeeland.",
    address: "Middelburg",
    postal_code: "",
    website: "https://www.happyescortzeeland.nl",
    image_url: "/screenshots/happy-escort-zeeland.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 3,
    is_verified: true,
    is_featured: false,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },
  {
    id: "excel-158",
    name: "Happy Escort Gelderland",
    slug: "happy-escort-gelderland",
    city_slug: "arnhem",
    category_slugs: ["escorts"],
    primary_category: "escorts",
    description: "Happy Escort Gelderland biedt professionele en discrete escortdiensten in Arnhem en omgeving. Betrouwbaar, punctueel en met een selectie van aantrekkelijke dames voor diverse gelegenheden.",
    short_description: "Escort service actief in heel Gelderland.",
    address: "Arnhem",
    postal_code: "",
    website: "https://www.happyescortgelderland.nl",
    image_url: "/screenshots/happy-escort-gelderland.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 3,
    is_verified: true,
    is_featured: false,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },
  {
    id: "excel-159",
    name: "Happy Escort Limburg",
    slug: "happy-escort-limburg",
    city_slug: "maastricht",
    category_slugs: ["escorts"],
    primary_category: "escorts",
    description: "Happy Escort Limburg biedt professionele en discrete escortdiensten in Maastricht en omgeving. Betrouwbaar, punctueel en met een selectie van aantrekkelijke dames voor diverse gelegenheden.",
    short_description: "Escort service actief in heel Limburg.",
    address: "Maastricht",
    postal_code: "",
    website: "https://www.happyescortlimburg.nl",
    image_url: "/screenshots/happy-escort-limburg.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 3,
    is_verified: true,
    is_featured: false,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },
  {
    id: "excel-160",
    name: "Happy Escort Groningen",
    slug: "happy-escort-groningen",
    city_slug: "groningen",
    category_slugs: ["escorts"],
    primary_category: "escorts",
    description: "Happy Escort Groningen biedt professionele en discrete escortdiensten in Groningen en omgeving. Betrouwbaar, punctueel en met een selectie van aantrekkelijke dames voor diverse gelegenheden.",
    short_description: "Escort service actief in heel Groningen.",
    address: "Groningen",
    postal_code: "",
    website: "https://www.happyescortgroningen.nl",
    image_url: "/screenshots/happy-escort-groningen.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 3,
    is_verified: true,
    is_featured: false,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },
  {
    id: "excel-161",
    name: "Happy Escort Drenthe",
    slug: "happy-escort-drenthe",
    city_slug: "assen",
    category_slugs: ["escorts"],
    primary_category: "escorts",
    description: "Happy Escort Drenthe biedt professionele en discrete escortdiensten in Assen en omgeving. Betrouwbaar, punctueel en met een selectie van aantrekkelijke dames voor diverse gelegenheden.",
    short_description: "Escort service actief in heel Drenthe.",
    address: "Assen",
    postal_code: "",
    website: "https://www.happyescortdrenthe.nl",
    image_url: "/screenshots/happy-escort-drenthe.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 3,
    is_verified: true,
    is_featured: false,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },
  {
    id: "excel-162",
    name: "Happy Escort Noord-Brabant",
    slug: "happy-escort-noord-brabant",
    city_slug: "eindhoven",
    category_slugs: ["escorts"],
    primary_category: "escorts",
    description: "Happy Escort Noord-Brabant biedt professionele en discrete escortdiensten in Eindhoven en omgeving. Betrouwbaar, punctueel en met een selectie van aantrekkelijke dames voor diverse gelegenheden.",
    short_description: "Escort service actief in heel Noord-Brabant.",
    address: "Eindhoven",
    postal_code: "",
    website: "https://www.happyescortnoordbrabant.nl",
    image_url: "/screenshots/happy-escort-noord-brabant.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 3,
    is_verified: true,
    is_featured: false,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },
  {
    id: "excel-163",
    name: "Happy Escort Friesland",
    slug: "happy-escort-friesland",
    city_slug: "leeuwarden",
    category_slugs: ["escorts"],
    primary_category: "escorts",
    description: "Happy Escort Friesland biedt professionele en discrete escortdiensten in Leeuwarden en omgeving. Betrouwbaar, punctueel en met een selectie van aantrekkelijke dames voor diverse gelegenheden.",
    short_description: "Escort service actief in heel Friesland.",
    address: "Leeuwarden",
    postal_code: "",
    website: "https://www.happyescortfriesland.nl",
    image_url: "/screenshots/happy-escort-friesland.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 3,
    is_verified: true,
    is_featured: false,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },
  {
    id: "excel-164",
    name: "Happy Escort Noord-Holland",
    slug: "happy-escort-noord-holland",
    city_slug: "amsterdam",
    category_slugs: ["escorts"],
    primary_category: "escorts",
    description: "Happy Escort Noord-Holland biedt professionele en discrete escortdiensten in Amsterdam en omgeving. Betrouwbaar, punctueel en met een selectie van aantrekkelijke dames voor diverse gelegenheden.",
    short_description: "Escort service actief in heel Noord-Holland.",
    address: "Amsterdam",
    postal_code: "",
    website: "https://www.happyescortnoordholland.nl",
    image_url: "/screenshots/happy-escort-noord-holland.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 3,
    is_verified: true,
    is_featured: false,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },
  {
    id: "excel-165",
    name: "Happy Escort Zuid-Holland",
    slug: "happy-escort-zuid-holland",
    city_slug: "rotterdam",
    category_slugs: ["escorts"],
    primary_category: "escorts",
    description: "Happy Escort Zuid-Holland biedt professionele en discrete escortdiensten in Rotterdam en omgeving. Betrouwbaar, punctueel en met een selectie van aantrekkelijke dames voor diverse gelegenheden.",
    short_description: "Escort service actief in heel Zuid-Holland.",
    address: "Rotterdam",
    postal_code: "",
    website: "https://www.happyescortzuidholland.nl",
    image_url: "/screenshots/happy-escort-zuid-holland.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 3,
    is_verified: true,
    is_featured: false,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },
  {
    id: "excel-166",
    name: "Happy Escort Overijssel",
    slug: "happy-escort-overijssel",
    city_slug: "zwolle",
    category_slugs: ["escorts"],
    primary_category: "escorts",
    description: "Happy Escort Overijssel biedt professionele en discrete escortdiensten in Zwolle en omgeving. Betrouwbaar, punctueel en met een selectie van aantrekkelijke dames voor diverse gelegenheden.",
    short_description: "Escort service actief in heel Overijssel.",
    address: "Zwolle",
    postal_code: "",
    website: "https://www.happyescortoverijssel.nl",
    image_url: "/screenshots/happy-escort-overijssel.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 3,
    is_verified: true,
    is_featured: false,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },
  {
    id: "excel-167",
    name: "Happy Escort Flevoland",
    slug: "happy-escort-flevoland",
    city_slug: "almere",
    category_slugs: ["escorts"],
    primary_category: "escorts",
    description: "Happy Escort Flevoland biedt professionele en discrete escortdiensten in Almere en omgeving. Betrouwbaar, punctueel en met een selectie van aantrekkelijke dames voor diverse gelegenheden.",
    short_description: "Escort service actief in heel Flevoland.",
    address: "Almere",
    postal_code: "",
    website: "https://www.happyescortflevoland.nl",
    image_url: "/screenshots/happy-escort-flevoland.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 3,
    is_verified: true,
    is_featured: false,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },
  {
    id: "excel-168",
    name: "Happy Escort Utrecht",
    slug: "happy-escort-utrecht",
    city_slug: "utrecht",
    category_slugs: ["escorts"],
    primary_category: "escorts",
    description: "Happy Escort Utrecht biedt professionele en discrete escortdiensten in Utrecht en omgeving. Betrouwbaar, punctueel en met een selectie van aantrekkelijke dames voor diverse gelegenheden.",
    short_description: "Escort service actief in heel Utrecht.",
    address: "Utrecht",
    postal_code: "",
    website: "https://www.happyescortutrecht.nl",
    image_url: "/screenshots/happy-escort-utrecht.jpg",
    average_rating: 0,
    review_count: 0,
    price_range: 3,
    is_verified: true,
    is_featured: false,
    created_at: "2025-01-01",
    updated_at: "2026-03-01",
  },
];

// ══════════════════════════════════════════════════════════════════════════════
// HELPER FUNCTIONS
// ══════════════════════════════════════════════════════════════════════════════

export function getRealBusinessesByCity(citySlug: string): Business[] {
  return realBusinesses.filter((b) => b.city_slug === citySlug);
}

export function getRealBusinessesByCategory(categorySlug: string): Business[] {
  return realBusinesses.filter((b) =>
    b.category_slugs.includes(categorySlug)
  );
}

export function getRealBusinessByCityAndCategory(
  citySlug: string,
  categorySlug: string
): Business[] {
  return realBusinesses.filter(
    (b) =>
      b.city_slug === citySlug && b.category_slugs.includes(categorySlug)
  );
}

export function getFeaturedRealBusinesses(): Business[] {
  return realBusinesses.filter((b) => b.is_featured);
}

export function getRealBusinessBySlug(
  citySlug: string,
  businessSlug: string
): Business | undefined {
  return realBusinesses.find(
    (b) => b.city_slug === citySlug && b.slug === businessSlug
  );
}

// Summary stats
export const realBusinessStats = {
  totalBusinesses: realBusinesses.length,
  cities: [...new Set(realBusinesses.map((b) => b.city_slug))],
  categories: [...new Set(realBusinesses.flatMap((b) => b.category_slugs))],
  featured: realBusinesses.filter((b) => b.is_featured).length,
  verified: realBusinesses.filter((b) => b.is_verified).length,
};
